"""add control treatment fields to recovery events

Revision ID: 361460832735
Revises: 1bebe81dded0
Create Date: 2026-09-01 22:59:25.293172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361460832735'
down_revision: Union[str, Sequence[str], None] = '1bebe81dded0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_events', sa.Column('is_control', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('recovery_events', sa.Column('experiment_id', sa.Integer(), nullable=True))
    op.add_column('recovery_events', sa.Column('variant', sa.String(length=20), nullable=True))
    op.drop_index(op.f('ix_recovery_events_payment_id'), table_name='recovery_events')
    op.create_index(op.f('ix_recovery_events_payment_id'), 'recovery_events', ['payment_id'], unique=True)
    op.create_index(op.f('ix_recovery_events_experiment_id'), 'recovery_events', ['experiment_id'], unique=False)
    op.create_foreign_key(
        'fk_recovery_events_experiment_id_experiments',
        'recovery_events',
        'experiments',
        ['experiment_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_recovery_events_experiment_id_experiments',
        'recovery_events',
        type_='foreignkey',
    )
    op.drop_index(op.f('ix_recovery_events_experiment_id'), table_name='recovery_events')
    op.drop_index(op.f('ix_recovery_events_payment_id'), table_name='recovery_events')
    op.create_index(op.f('ix_recovery_events_payment_id'), 'recovery_events', ['payment_id'], unique=False)
    op.drop_column('recovery_events', 'variant')
    op.drop_column('recovery_events', 'experiment_id')
    op.drop_column('recovery_events', 'is_control')
    # ### end Alembic commands ###
